config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord


  SPECIES = %w(pig bird lyon dog)

  validates :name, presence: true
  validates :species, inclusion: { in: SPECIES}

  def found_on
    "#{(Date.today - date).to_i} days ago"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  def index
    @pets = Pet.all
  end

  def show

  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pets_params)
    if @pet.save
      redirect_to pets_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @pet.update(pets_params)
      redirect_to pets_path
    else
      render :edit
    end
  end

  def destroy
    @pet.destroy
    redirect_to pets_path
  end

  private

  def pets_params
    params.require(:pet).permit(:name, :date, :species, :address)
  end

  def set_pet
    @pet = Pet.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lost</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<div class="container">
  <%= simple_form_for pet do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :date %>
    <%= f.input :species, collection: Pet::SPECIES %>
    <%= f.submit %>
  <% end %>
  <%= link_to "back", pets_path, class:"btn btn-primary" %>
</div>

app/views/pets/edit.html.erb
<%= render "form",  pet: @pet  %>

app/views/pets/index.html.erb
<div class="container">
  <h1>All Pets</h1>
  <%= link_to "New pet", new_pet_path, class:"btn btn-primary" %>
  <% @pets.each do |pet| %>
    <div class="card">
      <p><%= link_to pet.name, pet_path(pet) %></p>
      <p><%= pet.address  %></p>
      <p><%=  pet.species %></p>
      <p><%= pet.found_on %> </p>
    </div>
  <% end %>
</div>

app/views/pets/new.html.erb
<div class="container">
  <%= render "form", pet: @pet  %>
</div>

app/views/pets/show.html.erb
<div class="container">
  <%= link_to "New", new_pet_path, class: "btn btn-primary" %>
    <h1><%= @pet.name %></h1>
    <p><%= @pet.address  %></p>
    <p><%=  @pet.species %></p>
    <p><%= @pet.found_on %> </p>
    <%= link_to "back", pets_path, class:"btn btn-primary"  %>
    <%= link_to "Edit", edit_pet_path(@pet), class:"btn btn-info" %>
    <%= link_to "Delete", pet_path(@pet), method: :delete, data: { confirm: "Are you sure" }, class:"btn btn-danger" %>
</div>